"use client";
import {useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/lib/api";
import {CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {formatIST} from "@/components/desk-ui";
type Point={session:string;session_offset:number;return:number|null;spot_return:number|null;direction_return:number|null;mark_available_at:string|null;mark:number|null};
type Item={lane:string;source_session:string;rank:number;symbol:string;strike:number;option_type:string;expiry:string;entry_mark:number|null;entry_available_at?:string;model_version:string;qualified:boolean;entry_on_time:boolean;status:string;latest?:Point;paths:Point[];peak_return:number|null;adverse_return:number|null;peak_at?:string;first_reach:Record<string,{at:string;session_offset:number}>;missing_sessions:number};
type Quality={model_version:string;horizon:number;n:number;sessions:number;mean_return:number|null;median_return:number|null;positive_fraction:number|null;direction_hit_rate:number|null;direction_n:number;qualified_n:number};
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${(v*100).toFixed(2)}%`;
const money=(v:number|null|undefined)=>v==null?"—":v.toLocaleString("en-IN",{maximumFractionDigits:2});
const tone=(v:number|null|undefined)=>v==null?"text-text-muted":v>=0?"text-emerald-300":"text-rose-300";
export default function ObservationFollowup(){
 const [lane,setLane]=useState("swing"),[search,setSearch]=useState(""),[date,setDate]=useState(""),[selected,setSelected]=useState("");
 const query=useQuery({queryKey:["vanguard","observation-followup",lane],queryFn:async()=>(await api.get("/api/vanguard/observation-followup",{params:{lane}})).data as {items:Item[];quality:Quality[];status:string;updated_at:string;horizon_basis:string;validation:string},refetchInterval:60000});
 const items=useMemo(()=>query.data?.items||[],[query.data]);
 const filtered=items.filter(r=>(!date||r.source_session===date)&&`${r.symbol} ${r.strike} ${r.option_type}`.toLowerCase().includes(search.toLowerCase()));
 const key=(r:Item)=>`${r.source_session}-${r.rank}`;
 const current=filtered.find(r=>key(r)===selected)||filtered[0];
 const card="rounded-xl border border-bg-border bg-bg-secondary/40 p-4";
 return <div className="space-y-5">
 <section className={card}><p className="text-xs uppercase tracking-widest text-cyan-300">Frozen observations · research only</p><h2 className="mt-2 text-xl font-semibold">Follow each prediction through time</h2><p className="mt-2 text-sm text-text-secondary">Keep the original entry and exact option until expiry. Daily marks continue after the original 1–2-session outcome closes. Stock direction and premium return are measured separately; model versions remain frozen.</p><p className="mt-2 text-xs text-text-muted">Tracker updated {query.data?.updated_at?formatIST(query.data.updated_at):"—"}. Each row carries its own observed price time. Updates run with the market pipeline and end-of-day pass; late archive arrivals are reconciled on subsequent passes.</p></section>
 <div className="flex flex-wrap gap-3"><select aria-label="Observation lane" className={card} value={lane} onChange={e=>{setLane(e.target.value);setDate("");setSelected("")}}><option value="swing">Pre-close swing</option><option value="next_session">Next-session rankings</option></select><select aria-label="Observation date" className={card} value={date} onChange={e=>setDate(e.target.value)}><option value="">All list dates</option>{Array.from(new Set(items.map(r=>r.source_session))).map(d=><option key={d}>{d}</option>)}</select><input aria-label="Search observations" className={card} placeholder="Find GVT&D, INFY…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {query.isError?<p role="alert">Follow-through data could not be loaded.</p>:query.isLoading?<p>Loading observations…</p>:!items.length?<p>No persisted follow-through observations yet.</p>:null}
 {current&&<section className={card}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{current.symbol} {current.strike} {current.option_type} · {current.source_session}</h3><span className="text-xs text-text-muted">Expiry {current.expiry} · {current.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-xs text-text-secondary">Original entry ₹{money(current.entry_mark)} · {current.entry_available_at?formatIST(current.entry_available_at):"awaiting entry"}. Latest observed {current.latest?.mark_available_at?formatIST(current.latest.mark_available_at):"—"}.</p>
 <div className="my-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Premium since entry",pct(current.latest?.return)],["Underlying since entry",pct(current.latest?.spot_return)],["Observed peak",pct(current.peak_return)],["Observed adverse move",pct(current.adverse_return)]].map(([label,value])=><div key={label} className="rounded-lg bg-bg-primary/50 p-3"><p className="text-xs text-text-muted">{label}</p><p className="mt-1 font-mono text-lg">{value}</p></div>)}</div>
 <ResponsiveContainer width="100%" height={290}><LineChart data={current.paths.map(p=>({...p,premium:p.return==null?null:p.return*100,stock:p.spot_return==null?null:p.spot_return*100}))}><CartesianGrid stroke="#334155" strokeDasharray="3 3"/><XAxis dataKey="session" tickFormatter={v=>v.slice(5)} stroke="#94a3b8"/><YAxis unit="%" stroke="#94a3b8"/><Tooltip contentStyle={{background:"#0f172a",borderColor:"#334155"}} formatter={(value:number)=>`${value.toFixed(2)}%`}/><Legend/><Line type="linear" dataKey="premium" name="Option premium" stroke="#22d3ee" dot connectNulls={false}/><Line type="linear" dataKey="stock" name="Underlying" stroke="#a3e635" dot connectNulls={false}/></LineChart></ResponsiveContainer>
 <p className="mt-3 text-xs text-text-muted">Peak and adverse values use observed post-entry 30-minute highs/lows, not achievable exits. Missing sessions: {current.missing_sessions??0}. {current.entry_on_time===false?"Original entry was late; excluded from horizon quality scores.":""}</p>
 <div className="mt-3 flex flex-wrap gap-4 text-xs">{[.2,.4,.6,1].map(t=><span key={t}>First +{t*100}% close: {current.first_reach?.[String(t)]?`${current.first_reach[String(t)].at.slice(0,10)} · session +${current.first_reach[String(t)].session_offset}`:"not observed"}</span>)}</div></section>}
 <section className={card}><h3 className="font-semibold">Every observation · {filtered.length}</h3><div className="mt-3 max-h-[480px] overflow-auto"><table className="w-full whitespace-nowrap text-xs"><thead className="sticky top-0 bg-bg-secondary"><tr>{["List date / rank","Contract","Entry","Latest","Premium return","Stock direction return","Observed","Quality"].map(t=><th key={t} className="p-3 text-left">{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={key(r)} className="border-t border-bg-border hover:bg-bg-primary/40"><td className="p-3">{r.source_session} · #{r.rank}</td><td className="p-3"><button className="text-cyan-300 underline" onClick={()=>setSelected(key(r))}>{r.symbol} {r.strike} {r.option_type}</button></td><td className="p-3">{money(r.entry_mark)}</td><td className="p-3">{money(r.latest?.mark)}</td><td className={`p-3 ${tone(r.latest?.return)}`}>{pct(r.latest?.return)}</td><td className={`p-3 ${tone(r.latest?.direction_return)}`}>{pct(r.latest?.direction_return)}</td><td className="p-3">{r.latest?.mark_available_at?formatIST(r.latest.mark_available_at):"—"}</td><td className="p-3">{r.entry_on_time===false?"Late entry":r.qualified?"Qualified":"Research only"}</td></tr>)}</tbody></table></div></section>
 <section className={card}><h3 className="font-semibold">Prediction quality by fixed horizon</h3><p className="mt-2 text-xs text-text-secondary">{query.data?.horizon_basis} Scores cover the entire selected lane, independently of the symbol/date filter above. Missing or unfinished horizons are excluded, never filled with zero. Direction hit rate scores CE up / PE down on the underlying; premium win rate scores the option.</p><div className="mt-3 overflow-auto"><table className="w-full whitespace-nowrap text-xs"><thead><tr>{["Frozen model","Session +","Observed / source days","Mean premium","Median premium","Premium win rate","Direction hit rate","Qualified observations"].map(t=><th key={t} className="p-3 text-left">{t}</th>)}</tr></thead><tbody>{query.data?.quality.map(q=><tr key={`${q.model_version}-${q.horizon}`} className="border-t border-bg-border"><td className="max-w-[210px] truncate p-3" title={q.model_version}>{q.model_version}</td><td className="p-3">{q.horizon}</td><td className="p-3">{q.n} / {q.sessions}</td><td className={`p-3 ${tone(q.mean_return)}`}>{pct(q.mean_return)}</td><td className="p-3">{pct(q.median_return)}</td><td className="p-3">{pct(q.positive_fraction)}</td><td className="p-3">{pct(q.direction_hit_rate)} ({q.direction_n})</td><td className="p-3">{q.qualified_n}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-amber-200">{query.data?.validation} These descriptive samples are too short to establish predictive skill. Changing the horizon after seeing a winner is a research hypothesis, not validation.</p></section>
 </div>;
}
