"""Triple-barrier labeling for synthetic trade candidates.

This is the *secondary* Phase 0 path. The primary path labels actual historical round trips
(see `actual_trades.py`). The triple-barrier method here is for the next iteration where
we test what the model would have decided on synthetic candidates generated by MP-rule setups.

Given an entry timestamp, direction, stop, target, and max holding time, simulate the bar
forward path and report which barrier hit first, plus MFE/MAE and net R after cost.

Reference: López de Prado, *Advances in Financial Machine Learning*, Ch. 3.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Literal

import numpy as np
import pandas as pd

from nomad_sniper.utils.timeutil import ensure_ist


@dataclass
class TripleBarrierLabel:
    entry_time: datetime
    exit_time: datetime
    exit_reason: Literal["target", "stop", "timeout"]
    entry_price: float
    exit_price: float
    risk: float                 # rupees per unit at entry (= |entry - stop|)
    realised_r: float           # (exit - entry) * sign / risk
    mfe: float                  # max favourable excursion, rupees
    mae: float                  # max adverse excursion, rupees
    mfe_r: float
    mae_r: float


def label_triple_barrier(
    bars: pd.DataFrame,
    entry_time: datetime,
    direction: Literal["long", "short"],
    *,
    stop_price: float,
    target_price: float,
    max_holding: timedelta,
) -> TripleBarrierLabel | None:
    """Walk bars forward from `entry_time` until target, stop, or timeout hits.

    Returns None if there aren't enough forward bars (e.g. session ended).
    """
    entry_time = ensure_ist(entry_time)
    forward = bars[bars.index > entry_time]
    if forward.empty:
        return None

    deadline = entry_time + max_holding
    forward = forward[forward.index <= deadline]
    if forward.empty:
        return None

    # Entry price = open of the first forward bar (executable price)
    entry_bar = forward.iloc[0]
    entry_price = float(entry_bar["open"])

    if direction == "long":
        if not (stop_price < entry_price < target_price):
            raise ValueError(
                f"Long requires stop ({stop_price}) < entry ({entry_price}) < target ({target_price})"
            )
        risk = entry_price - stop_price
        sign = 1.0
    else:
        if not (target_price < entry_price < stop_price):
            raise ValueError(
                f"Short requires target ({target_price}) < entry ({entry_price}) < stop ({stop_price})"
            )
        risk = stop_price - entry_price
        sign = -1.0

    mfe = 0.0
    mae = 0.0

    for ts, bar in forward.iterrows():
        high = float(bar["high"])
        low = float(bar["low"])

        # Track excursions
        if direction == "long":
            fav = high - entry_price
            adv = entry_price - low
        else:
            fav = entry_price - low
            adv = high - entry_price
        mfe = max(mfe, fav)
        mae = max(mae, adv)

        # Check barriers — pessimistic ordering: if both hit in same bar, assume stop first.
        if direction == "long":
            stop_hit = low <= stop_price
            target_hit = high >= target_price
        else:
            stop_hit = high >= stop_price
            target_hit = low <= target_price

        if stop_hit and target_hit:
            exit_price = stop_price
            exit_reason: Literal["target", "stop", "timeout"] = "stop"
        elif stop_hit:
            exit_price = stop_price
            exit_reason = "stop"
        elif target_hit:
            exit_price = target_price
            exit_reason = "target"
        else:
            continue

        return TripleBarrierLabel(
            entry_time=entry_time,
            exit_time=ensure_ist(ts.to_pydatetime()),
            exit_reason=exit_reason,
            entry_price=entry_price,
            exit_price=float(exit_price),
            risk=risk,
            realised_r=sign * (exit_price - entry_price) / risk,
            mfe=mfe,
            mae=mae,
            mfe_r=mfe / risk,
            mae_r=mae / risk,
        )

    # Timeout: exit at the last bar's close
    last_bar = forward.iloc[-1]
    exit_price = float(last_bar["close"])
    return TripleBarrierLabel(
        entry_time=entry_time,
        exit_time=ensure_ist(forward.index[-1].to_pydatetime()),
        exit_reason="timeout",
        entry_price=entry_price,
        exit_price=exit_price,
        risk=risk,
        realised_r=sign * (exit_price - entry_price) / risk,
        mfe=mfe,
        mae=mae,
        mfe_r=mfe / risk,
        mae_r=mae / risk,
    )
