-- ============================================================================
-- Phantom index-expiry cleanup for option_premium_candles
-- ----------------------------------------------------------------------------
-- Generated by analysis.expiry_integrity (era-aware NSE Thu->Tue Sept-2025 rule).
-- These are NSE/BSE INDEX option series stamped on a weekday the exchange does
-- NOT list (e.g. NIFTY 2026-06-25 Thursday; NSE indices expire Tuesday/06-30).
-- Pre-migration Thursday history (e.g. NIFTY 2025-06-26) is NOT included.
--
-- Scope (verified read-only against the local DB):
--   32 (underlying, expiry) pairs  ->  32,387 rows  (0.23% of 13,807,948 total)
--
-- !! DO NOT RUN BLINDLY. Review the pair list, run the SELECT first, confirm the
-- !! count, THEN run the DELETE inside the transaction and COMMIT only if correct.
-- !! On PROD, take a backup/snapshot first.
-- ============================================================================

-- (1) Dry-run: how many rows match, broken down by pair.
SELECT underlying, expiry::text, count(*) AS rows, count(DISTINCT strike) AS strikes
FROM option_premium_candles
WHERE (underlying, expiry) IN (
  ('BANKEX', DATE '2026-04-30'),
  ('BANKNIFTY', DATE '2026-04-22'),
  ('BANKNIFTY', DATE '2026-04-23'),
  ('BANKNIFTY', DATE '2026-04-24'),
  ('BANKNIFTY', DATE '2026-04-29'),
  ('BANKNIFTY', DATE '2026-04-30'),
  ('BANKNIFTY', DATE '2026-05-28'),
  ('BANKNIFTY', DATE '2026-05-29'),
  ('FINNIFTY', DATE '2026-04-22'),
  ('FINNIFTY', DATE '2026-04-23'),
  ('FINNIFTY', DATE '2026-04-24'),
  ('FINNIFTY', DATE '2026-04-30'),
  ('FINNIFTY', DATE '2026-05-28'),
  ('FINNIFTY', DATE '2026-05-29'),
  ('MIDCPNIFTY', DATE '2026-04-22'),
  ('MIDCPNIFTY', DATE '2026-04-23'),
  ('MIDCPNIFTY', DATE '2026-04-24'),
  ('MIDCPNIFTY', DATE '2026-04-30'),
  ('MIDCPNIFTY', DATE '2026-05-28'),
  ('MIDCPNIFTY', DATE '2026-05-29'),
  ('NIFTY', DATE '2026-04-22'),
  ('NIFTY', DATE '2026-04-23'),
  ('NIFTY', DATE '2026-04-24'),
  ('NIFTY', DATE '2026-04-30'),
  ('NIFTY', DATE '2026-05-28'),
  ('NIFTY', DATE '2026-05-29'),
  ('NIFTY', DATE '2026-06-25'),
  ('NIFTYNXT50', DATE '2026-04-22'),
  ('NIFTYNXT50', DATE '2026-04-23'),
  ('NIFTYNXT50', DATE '2026-04-30'),
  ('SENSEX', DATE '2026-04-24'),
  ('SENSEX', DATE '2026-05-29')
)
GROUP BY underlying, expiry
ORDER BY underlying, expiry;

-- (2) Cleanup (run only after confirming the dry-run count == 32,387).
BEGIN;
DELETE FROM option_premium_candles
WHERE (underlying, expiry) IN (
  ('BANKEX', DATE '2026-04-30'),
  ('BANKNIFTY', DATE '2026-04-22'),
  ('BANKNIFTY', DATE '2026-04-23'),
  ('BANKNIFTY', DATE '2026-04-24'),
  ('BANKNIFTY', DATE '2026-04-29'),
  ('BANKNIFTY', DATE '2026-04-30'),
  ('BANKNIFTY', DATE '2026-05-28'),
  ('BANKNIFTY', DATE '2026-05-29'),
  ('FINNIFTY', DATE '2026-04-22'),
  ('FINNIFTY', DATE '2026-04-23'),
  ('FINNIFTY', DATE '2026-04-24'),
  ('FINNIFTY', DATE '2026-04-30'),
  ('FINNIFTY', DATE '2026-05-28'),
  ('FINNIFTY', DATE '2026-05-29'),
  ('MIDCPNIFTY', DATE '2026-04-22'),
  ('MIDCPNIFTY', DATE '2026-04-23'),
  ('MIDCPNIFTY', DATE '2026-04-24'),
  ('MIDCPNIFTY', DATE '2026-04-30'),
  ('MIDCPNIFTY', DATE '2026-05-28'),
  ('MIDCPNIFTY', DATE '2026-05-29'),
  ('NIFTY', DATE '2026-04-22'),
  ('NIFTY', DATE '2026-04-23'),
  ('NIFTY', DATE '2026-04-24'),
  ('NIFTY', DATE '2026-04-30'),
  ('NIFTY', DATE '2026-05-28'),
  ('NIFTY', DATE '2026-05-29'),
  ('NIFTY', DATE '2026-06-25'),
  ('NIFTYNXT50', DATE '2026-04-22'),
  ('NIFTYNXT50', DATE '2026-04-23'),
  ('NIFTYNXT50', DATE '2026-04-30'),
  ('SENSEX', DATE '2026-04-24'),
  ('SENSEX', DATE '2026-05-29')
);
-- Verify the DELETE affected the expected number of rows, then:
--   COMMIT;   -- if correct
--   ROLLBACK; -- if anything looks off
ROLLBACK;  -- <-- default is ROLLBACK; change to COMMIT deliberately.
