"""Static research taxonomy for macro, sector, and frontier-theme scoring.

The live service enriches this catalog with public feeds. The catalog remains
explicit so trading agents can reason over stable data points even when public
feeds are delayed or unavailable.
"""
from __future__ import annotations

from typing import Any


MACRO_INDICATORS: list[dict[str, Any]] = [
    {
        "id": "india_gdp_growth",
        "label": "India real GDP growth",
        "country": "IND",
        "world_bank_code": "NY.GDP.MKTP.KD.ZG",
        "unit": "%",
        "fallback_value": 8.2,
        "fallback_year": "2024",
        "good_direction": "higher",
        "influences": ["demand", "credit", "capex", "earnings"],
    },
    {
        "id": "india_inflation",
        "label": "India CPI inflation",
        "country": "IND",
        "world_bank_code": "FP.CPI.TOTL.ZG",
        "unit": "%",
        "fallback_value": 5.7,
        "fallback_year": "2024",
        "good_direction": "lower",
        "influences": ["rates", "margins", "consumption"],
    },
    {
        "id": "india_lending_rate",
        "label": "India lending rate",
        "country": "IND",
        "world_bank_code": "FR.INR.LEND",
        "unit": "%",
        "fallback_value": 9.3,
        "fallback_year": "2024",
        "good_direction": "lower",
        "influences": ["autos", "realty", "nbfc", "capex"],
    },
    {
        "id": "india_consumption_growth",
        "label": "India household consumption growth",
        "country": "IND",
        "world_bank_code": "NE.CON.PRVT.KD.ZG",
        "unit": "%",
        "fallback_value": 4.0,
        "fallback_year": "2024",
        "good_direction": "higher",
        "influences": ["fmcg", "auto", "retail", "durables"],
    },
    {
        "id": "world_gdp_growth",
        "label": "World real GDP growth",
        "country": "WLD",
        "world_bank_code": "NY.GDP.MKTP.KD.ZG",
        "unit": "%",
        "fallback_value": 2.7,
        "fallback_year": "2024",
        "good_direction": "higher",
        "influences": ["exports", "it_services", "metals", "energy"],
    },
    {
        "id": "world_inflation",
        "label": "World CPI inflation",
        "country": "WLD",
        "world_bank_code": "FP.CPI.TOTL.ZG",
        "unit": "%",
        "fallback_value": 5.5,
        "fallback_year": "2024",
        "good_direction": "lower",
        "influences": ["rates", "commodities", "risk_appetite"],
    },
]


COMMODITY_WATCHLIST: list[dict[str, Any]] = [
    {
        "code": "CRUDE",
        "label": "Crude oil",
        "stooq_symbol": "cl.f",
        "unit": "USD/bbl",
        "fallback_price": 82.4,
        "fallback_change_pct": -0.6,
        "beneficiaries": ["UPSTREAM_ENERGY"],
        "hurt_by_rise": ["AUTO", "FMCG", "CEMENT", "PAINTS", "AVIATION", "OMC"],
        "why": "Fuel, freight, packaging, and petrochemical input costs.",
    },
    {
        "code": "GOLD",
        "label": "Gold",
        "stooq_symbol": "gc.f",
        "unit": "USD/oz",
        "fallback_price": 2320.0,
        "fallback_change_pct": 0.4,
        "beneficiaries": ["JEWELLERY", "GOLD_FINANCE"],
        "hurt_by_rise": ["DISCRETIONARY_CONSUMPTION"],
        "why": "Risk hedge, jewellery affordability, and collateral value for gold-loan books.",
    },
    {
        "code": "COPPER",
        "label": "Copper",
        "stooq_symbol": "hg.f",
        "unit": "US cents/lb",
        "fallback_price": 456.0,
        "fallback_change_pct": 0.9,
        "beneficiaries": ["METALS", "MINING"],
        "hurt_by_rise": ["CONSUMER_DURABLES", "CAPITAL_GOODS", "AUTO"],
        "why": "Electrification demand proxy and input cost for cables, motors, white goods, and EVs.",
    },
    {
        "code": "STEEL",
        "label": "Steel basket",
        "stooq_symbol": None,
        "unit": "index",
        "fallback_price": 100.0,
        "fallback_change_pct": 0.2,
        "beneficiaries": ["METALS"],
        "hurt_by_rise": ["AUTO", "REALTY_INFRA", "CAPITAL_GOODS"],
        "why": "High steel prices help producers but pressure autos, construction, and machinery margins.",
    },
    {
        "code": "PALM_OIL",
        "label": "Palm oil",
        "stooq_symbol": None,
        "unit": "index",
        "fallback_price": 100.0,
        "fallback_change_pct": -0.4,
        "beneficiaries": [],
        "hurt_by_rise": ["FMCG", "QSR"],
        "why": "Soap, packaged food, and edible-oil gross-margin driver.",
    },
]


SECTOR_RESEARCH_CATALOG: list[dict[str, Any]] = [
    {
        "code": "AUTO",
        "label": "Auto and Auto Ancillaries",
        "theme_queries": ["auto sales india", "electric vehicle india", "two wheeler demand india"],
        "frontier_queries": ["electric vehicle battery", "solid state battery", "charging infrastructure"],
        "base_score": 63,
        "drivers": [
            "Passenger vehicle, two-wheeler, tractor, and commercial vehicle dispatch growth",
            "EV penetration, hybrid adoption, charging network expansion, and battery cost decline",
            "Rural income, monsoon, replacement demand, and financing availability",
            "Export recovery for ancillaries and premiumization in SUVs and motorcycles",
        ],
        "draggers": [
            "Higher lending rates and tighter retail finance",
            "Steel, aluminium, rubber, copper, and crude-linked cost pressure",
            "EV cannibalization risk for legacy ICE leaders and dealer inventory stress",
            "Regulatory transitions that raise upfront vehicle cost",
        ],
        "research_points": [
            {"metric": "Monthly sales growth", "cadence": "monthly", "signal": "PV/2W/CV/tractor YoY and MoM split"},
            {"metric": "EV mix", "cadence": "monthly", "signal": "EV registrations as percentage of segment sales"},
            {"metric": "Dealer inventory", "cadence": "monthly", "signal": "Inventory days and discounting intensity"},
            {"metric": "Input basket", "cadence": "weekly", "signal": "Steel, rubber, aluminium, copper, crude"},
            {"metric": "Finance pressure", "cadence": "monthly", "signal": "Auto-loan rates and approval tightness"},
        ],
        "leaders": ["MARUTI", "M&M", "TVSMOTOR", "EICHERMOT", "BAJAJ-AUTO", "SONACOMS", "EXIDEIND"],
        "agent_uses": ["sector strength", "EV transition filter", "margin pressure warning", "earnings setup"],
    },
    {
        "code": "BANKING",
        "label": "Banks and Credit",
        "theme_queries": ["india credit growth", "deposit growth india banks", "net interest margin banks india"],
        "frontier_queries": ["digital lending risk", "banking AI underwriting", "account aggregator lending"],
        "base_score": 59,
        "drivers": [
            "System credit growth, deposit mobilization, CASA stability, and fee income",
            "Lower credit costs, stable asset quality, and recoveries",
            "Liquidity conditions and yield-curve behavior",
            "Digital origination and risk-pricing efficiency",
        ],
        "draggers": [
            "Deposit repricing faster than loan repricing",
            "RBI tightening, unsecured-loan stress, and NPA formation",
            "Bond yield spikes that hurt treasury books",
            "Crowded ownership in large private banks",
        ],
        "research_points": [
            {"metric": "Credit growth", "cadence": "fortnightly", "signal": "System credit YoY and deposit YoY spread"},
            {"metric": "NIM direction", "cadence": "quarterly", "signal": "NIM and cost-of-funds trend"},
            {"metric": "Asset quality", "cadence": "quarterly", "signal": "GNPA, slippages, SMA, credit cost"},
            {"metric": "Liquidity", "cadence": "daily", "signal": "Call money, LAF balance, bond yields"},
        ],
        "leaders": ["HDFCBANK", "ICICIBANK", "KOTAKBANK", "SBIN", "AXISBANK", "FEDERALBNK"],
        "agent_uses": ["rate sensitivity", "credit cycle filter", "index leadership", "risk-off warning"],
    },
    {
        "code": "FINANCIALS",
        "label": "NBFC, Insurance, AMCs and Market Infra",
        "theme_queries": ["india nbfc loan growth", "insurance premium growth india", "mutual fund flows india"],
        "frontier_queries": ["wealthtech india", "insurtech india", "tokenized securities market infrastructure"],
        "base_score": 57,
        "drivers": [
            "Retail credit demand, gold-loan collateral values, housing finance growth, and market volumes",
            "Equity inflows, SIP additions, insurance premium growth, and exchange volumes",
            "Stable spreads and access to wholesale funding",
        ],
        "draggers": [
            "Higher rates, ALM stress, funding spread widening, and regulatory caps",
            "Equity market drawdowns reducing AMC and broker fee pools",
            "Unsecured credit cycle deterioration",
        ],
        "research_points": [
            {"metric": "AUM and SIP flows", "cadence": "monthly", "signal": "MF gross inflow, SIP additions, equity AUM"},
            {"metric": "Loan growth", "cadence": "quarterly", "signal": "AUM growth and disbursement trend"},
            {"metric": "Funding spread", "cadence": "weekly", "signal": "CP/NCD spreads and bond yields"},
            {"metric": "Market activity", "cadence": "daily", "signal": "Cash/F&O turnover, demat additions"},
        ],
        "leaders": ["BAJFINANCE", "BAJAJFINSV", "JIOFIN", "HDFCAMC", "CDSL", "BSE", "MCX", "MUTHOOTFIN"],
        "agent_uses": ["risk appetite proxy", "retail activity", "credit spread pressure", "beta leadership"],
    },
    {
        "code": "IT",
        "label": "IT Services and Digital Engineering",
        "theme_queries": ["IT services demand India", "BFSI tech spending", "AI cloud migration enterprise"],
        "frontier_queries": ["generative AI software engineering", "agentic AI enterprise", "cloud modernization"],
        "base_score": 54,
        "drivers": [
            "US and Europe discretionary tech spending, deal TCV, cloud migration, and AI transformation",
            "INR depreciation supporting margins",
            "Utilization recovery and hiring stabilization",
            "Engineering R&D demand for auto, aerospace, and industrial clients",
        ],
        "draggers": [
            "BFSI client cuts, furloughs, and delayed decision cycles",
            "Wage hikes, attrition, visa costs, and pricing pressure",
            "AI-led productivity deflation if not monetized",
        ],
        "research_points": [
            {"metric": "Deal TCV", "cadence": "quarterly", "signal": "Large-deal wins and book-to-bill"},
            {"metric": "Client budget commentary", "cadence": "quarterly", "signal": "BFSI, retail, manufacturing demand"},
            {"metric": "Currency", "cadence": "daily", "signal": "INR/USD and cross-currency movement"},
            {"metric": "Hiring", "cadence": "quarterly", "signal": "Headcount, utilization, subcontracting"},
        ],
        "leaders": ["TCS", "INFY", "HCLTECH", "TECHM", "PERSISTENT", "COFORGE", "KPITTECH"],
        "agent_uses": ["export demand proxy", "currency hedge", "earnings commentary retrieval", "AI disruption watch"],
    },
    {
        "code": "FMCG",
        "label": "FMCG and Staples",
        "theme_queries": ["rural demand india FMCG", "consumer staples volume growth india", "palm oil prices FMCG margins"],
        "frontier_queries": ["quick commerce FMCG", "consumer premiumization India", "retail media advertising"],
        "base_score": 56,
        "drivers": [
            "Rural wage growth, monsoon, food inflation normalization, and volume recovery",
            "Premiumization, quick commerce distribution, and ad-spend efficiency",
            "Palm oil, crude derivatives, packaging, and freight cost relief",
        ],
        "draggers": [
            "Food inflation hurting discretionary volumes",
            "Palm oil, crude derivatives, packaging, and freight spikes",
            "Local competition and downtrading in rural packs",
        ],
        "research_points": [
            {"metric": "Volume growth", "cadence": "quarterly", "signal": "Urban/rural volume split"},
            {"metric": "Input costs", "cadence": "weekly", "signal": "Palm oil, crude derivatives, packaging"},
            {"metric": "Rural proxy", "cadence": "monthly", "signal": "Wages, tractor sales, rainfall, MGNREGA demand"},
            {"metric": "Channel shift", "cadence": "monthly", "signal": "Quick commerce share and distributor commentary"},
        ],
        "leaders": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "MARICO", "VBL"],
        "agent_uses": ["defensive rotation", "rural demand filter", "margin expansion", "inflation sensitivity"],
    },
    {
        "code": "METALS",
        "label": "Metals and Mining",
        "theme_queries": ["china steel demand", "iron ore prices", "india metals demand infrastructure"],
        "frontier_queries": ["green steel hydrogen", "battery metals demand", "aluminium EV demand"],
        "base_score": 52,
        "drivers": [
            "China PMI, global manufacturing, infrastructure capex, and domestic construction demand",
            "Iron ore, coking coal, aluminium, zinc, and copper price momentum",
            "USD trend and export realizations",
        ],
        "draggers": [
            "China slowdown, dumping risk, and import competition",
            "Coking coal and power cost spikes",
            "Environmental restrictions and tariff uncertainty",
        ],
        "research_points": [
            {"metric": "China PMI", "cadence": "monthly", "signal": "Manufacturing expansion/contraction"},
            {"metric": "Metal spreads", "cadence": "daily", "signal": "LME/spot price and raw material spread"},
            {"metric": "Inventory", "cadence": "weekly", "signal": "Exchange inventory and domestic channel stock"},
            {"metric": "Policy", "cadence": "event", "signal": "Duties, export curbs, dumping probes"},
        ],
        "leaders": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL", "JINDALSTEL", "NATIONALUM"],
        "agent_uses": ["global growth proxy", "commodity beta", "risk-on confirmation", "cost-spread watch"],
    },
    {
        "code": "ENERGY",
        "label": "Energy, Oil and Power",
        "theme_queries": ["india power demand", "crude oil price india", "renewable energy capacity india"],
        "frontier_queries": ["grid scale battery storage", "green hydrogen", "renewable energy forecasting"],
        "base_score": 61,
        "drivers": [
            "Power demand growth, capacity addition, tariff visibility, and renewable tender momentum",
            "Crude and gas prices for upstream producers and refiners",
            "Policy support for storage, green hydrogen, transmission, and distribution reforms",
        ],
        "draggers": [
            "Fuel under-recoveries, subsidy burden, regulatory tariff caps, and coal availability",
            "High capex leverage and execution delays",
            "Crude volatility hurting OMCs and downstream margins",
        ],
        "research_points": [
            {"metric": "Power demand", "cadence": "daily", "signal": "Peak demand, PLF, merchant power prices"},
            {"metric": "Crude/gas", "cadence": "daily", "signal": "Brent/WTI, LNG, refining cracks"},
            {"metric": "Tender pipeline", "cadence": "monthly", "signal": "Solar/wind/storage awards and tariffs"},
            {"metric": "Policy", "cadence": "event", "signal": "Subsidy, windfall tax, RPO and transmission rules"},
        ],
        "leaders": ["RELIANCE", "ONGC", "NTPC", "POWERGRID", "TATAPOWER", "JSWENERGY", "SUZLON"],
        "agent_uses": ["commodity shock filter", "power demand proxy", "renewable theme discovery", "policy catalyst"],
    },
    {
        "code": "HEALTHCARE",
        "label": "Healthcare and Pharma",
        "theme_queries": ["USFDA approvals India pharma", "India healthcare demand", "API prices pharma"],
        "frontier_queries": ["biosimilars", "GLP-1 obesity drugs", "AI drug discovery", "precision medicine"],
        "base_score": 58,
        "drivers": [
            "US generics approvals, specialty launches, biosimilars, and domestic chronic therapy growth",
            "Hospital occupancy, ARPOB, insurance penetration, and medical tourism",
            "INR depreciation and API cost normalization",
        ],
        "draggers": [
            "USFDA warning letters, price erosion, plant remediation cost",
            "API cost spikes, adverse currency moves, and litigation",
            "Regulatory price controls in domestic formulations",
        ],
        "research_points": [
            {"metric": "USFDA flow", "cadence": "event", "signal": "Approvals, observations, warning letters"},
            {"metric": "Price erosion", "cadence": "quarterly", "signal": "US generic pricing and launches"},
            {"metric": "Hospital metrics", "cadence": "quarterly", "signal": "Occupancy, ARPOB, bed additions"},
            {"metric": "API costs", "cadence": "monthly", "signal": "China API availability and prices"},
        ],
        "leaders": ["SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "APOLLOHOSP", "MAXHEALTH", "LUPIN"],
        "agent_uses": ["defensive growth", "regulatory event gate", "currency beneficiary", "earnings catalyst"],
    },
    {
        "code": "REALTY_INFRA",
        "label": "Realty, Infra and Construction Materials",
        "theme_queries": ["India housing sales", "India infrastructure capex", "cement demand India"],
        "frontier_queries": ["proptech India", "modular construction", "green cement"],
        "base_score": 60,
        "drivers": [
            "Housing affordability, launches, absorption, registrations, and government capex",
            "Roads, railways, airports, data centers, logistics, and urban infrastructure order flow",
            "Cement pricing discipline and fuel cost relief",
        ],
        "draggers": [
            "Mortgage-rate pressure, inventory pile-up, approval delays, and leverage",
            "Coal, petcoke, freight, steel, and land-cost inflation",
            "Election or budget delays in government ordering",
        ],
        "research_points": [
            {"metric": "Housing absorption", "cadence": "quarterly", "signal": "Sales, launches, inventory months"},
            {"metric": "Mortgage affordability", "cadence": "monthly", "signal": "Home-loan rate and EMI/income"},
            {"metric": "Order inflow", "cadence": "quarterly", "signal": "Infra awards and L1 pipeline"},
            {"metric": "Fuel costs", "cadence": "weekly", "signal": "Petcoke, coal, diesel freight"},
        ],
        "leaders": ["DLF", "LODHA", "GODREJPROP", "OBEROIRLTY", "LT", "ULTRACEMCO", "AMBUJACEM"],
        "agent_uses": ["domestic capex cycle", "rate sensitivity", "budget theme", "cement margin pressure"],
    },
    {
        "code": "INDUSTRIALS",
        "label": "Industrials, Defence and Capital Goods",
        "theme_queries": ["India capex cycle", "defence orders India", "railway capex India"],
        "frontier_queries": ["industrial automation India", "defence electronics", "robotics manufacturing"],
        "base_score": 66,
        "drivers": [
            "Private capex revival, government ordering, defence indigenization, and railway modernization",
            "Order book growth, execution speed, and operating leverage",
            "Export opportunities in electronics, aerospace, and industrial systems",
        ],
        "draggers": [
            "Valuation crowding, execution bottlenecks, delayed ordering, and working-capital stress",
            "Copper, steel, electronics, and freight cost pressure",
            "Policy or procurement timeline risk",
        ],
        "research_points": [
            {"metric": "Order inflow", "cadence": "quarterly", "signal": "Book-to-bill and tender pipeline"},
            {"metric": "Execution", "cadence": "quarterly", "signal": "Revenue conversion and margin"},
            {"metric": "PMI/capex", "cadence": "monthly", "signal": "Manufacturing PMI, IIP capital goods"},
            {"metric": "Policy", "cadence": "event", "signal": "Defence approvals and PLI updates"},
        ],
        "leaders": ["L&T", "ABB", "SIEMENS", "HAL", "BEL", "BHEL", "CGPOWER", "KAYNES"],
        "agent_uses": ["capex leadership", "defence theme", "order-flow catalyst", "valuation risk flag"],
    },
    {
        "code": "CONSUMER_DURABLES",
        "label": "Consumer Durables and Electronics",
        "theme_queries": ["consumer durables India demand", "AC sales India heatwave", "electronics manufacturing India"],
        "frontier_queries": ["electronics manufacturing services India", "smart appliances", "power electronics"],
        "base_score": 62,
        "drivers": [
            "Premiumization, heatwaves, housing cycle, festive demand, and electronics localization",
            "PLI-led manufacturing, component ecosystem expansion, and export orders",
            "Stable copper, aluminium, plastic, and freight costs",
        ],
        "draggers": [
            "High discretionary rates, weak rural demand, and inventory discounting",
            "Copper, aluminium, compressor, and semiconductor cost spikes",
            "Import policy or supply-chain disruption",
        ],
        "research_points": [
            {"metric": "Category sales", "cadence": "monthly", "signal": "AC, appliances, jewellery, electronics growth"},
            {"metric": "Input basket", "cadence": "weekly", "signal": "Copper, aluminium, plastics, freight"},
            {"metric": "Weather demand", "cadence": "weekly", "signal": "Heatwave intensity and power demand"},
            {"metric": "PLI/exports", "cadence": "monthly", "signal": "EMS order wins and export mix"},
        ],
        "leaders": ["DIXON", "AMBER", "VOLTAS", "BLUESTARCO", "HAVELLS", "TITAN", "TRENT"],
        "agent_uses": ["discretionary demand", "weather catalyst", "manufacturing theme", "input-cost watch"],
    },
    {
        "code": "DIGITAL_SERVICES",
        "label": "Telecom, Internet and Digital Services",
        "theme_queries": ["India telecom ARPU", "quick commerce India", "digital payments India"],
        "frontier_queries": ["5G private networks", "quick commerce logistics", "AI advertising marketplace"],
        "base_score": 64,
        "drivers": [
            "Tariff hikes, ARPU expansion, data growth, quick commerce adoption, and digital advertising",
            "Operating leverage after capex and logistics density improvement",
            "Payments, travel, food delivery, and platform monetization",
        ],
        "draggers": [
            "High 5G capex, spectrum costs, competitive subsidies, and regulatory fees",
            "Cash burn in quick commerce or food delivery",
            "Ad-cycle slowdown and platform regulation",
        ],
        "research_points": [
            {"metric": "ARPU/subscribers", "cadence": "quarterly", "signal": "ARPU, churn, data consumption"},
            {"metric": "GMV/order growth", "cadence": "quarterly", "signal": "Quick commerce and food delivery volume"},
            {"metric": "Unit economics", "cadence": "quarterly", "signal": "Contribution margin and ad monetization"},
            {"metric": "Regulation", "cadence": "event", "signal": "Fees, data rules, platform controls"},
        ],
        "leaders": ["BHARTIARTL", "ETERNAL", "SWIGGY", "INDIGO", "PAYTM", "INDHOTEL"],
        "agent_uses": ["platform momentum", "tariff catalyst", "consumer internet beta", "cash-burn warning"],
    },
]


BUDDING_THEMES: list[dict[str, Any]] = [
    {
        "code": "DEFENCE_ELECTRONICS",
        "label": "Defence electronics and aerospace",
        "sector_code": "INDUSTRIALS",
        "queries": ["defence electronics India", "aerospace manufacturing India", "radar systems India"],
        "frontier_queries": ["software defined radar", "loitering munition", "unmanned systems autonomy"],
        "base_score": 72,
        "why_now": "Indigenization, export approvals, order-book visibility, and electronics content growth.",
        "watch": ["BEL", "HAL", "BDL", "MAZDOCK", "SOLARINDS", "KAYNES"],
    },
    {
        "code": "POWER_ELECTRONICS",
        "label": "Power electronics and grid hardware",
        "sector_code": "INDUSTRIALS",
        "queries": ["power electronics India", "grid capex India", "transformer demand India"],
        "frontier_queries": ["wide bandgap semiconductors", "silicon carbide power electronics", "smart grid hardware"],
        "base_score": 70,
        "why_now": "Renewables, EV chargers, data centers, railway electrification, and grid modernization.",
        "watch": ["CGPOWER", "ABB", "SIEMENS", "HAVELLS", "KEI", "POLYCAB"],
    },
    {
        "code": "EV_SUPPLY_CHAIN",
        "label": "EV supply chain and batteries",
        "sector_code": "AUTO",
        "queries": ["EV sales India", "battery manufacturing India", "charging infrastructure India"],
        "frontier_queries": ["solid state battery", "sodium ion battery", "battery recycling"],
        "base_score": 68,
        "why_now": "Falling battery costs, fleet electrification, policy support, and charging buildout.",
        "watch": ["EXIDEIND", "SONACOMS", "TVSMOTOR", "M&M", "TATAPOWER", "AMARAJABAT"],
    },
    {
        "code": "EMS_SEMICON",
        "label": "EMS, semiconductors and components",
        "sector_code": "CONSUMER_DURABLES",
        "queries": ["electronics manufacturing India", "semiconductor India", "PLI electronics India"],
        "frontier_queries": ["advanced packaging semiconductor", "chiplet packaging", "electronics manufacturing services"],
        "base_score": 69,
        "why_now": "Localization, PLI, export substitution, and component ecosystem formation.",
        "watch": ["DIXON", "KAYNES", "TATATECH", "PGEL", "AMBER"],
    },
    {
        "code": "QUICK_COMMERCE",
        "label": "Quick commerce and local logistics",
        "sector_code": "DIGITAL_SERVICES",
        "queries": ["quick commerce India", "dark stores India", "instant delivery profitability"],
        "frontier_queries": ["route optimization AI logistics", "micro fulfillment automation", "retail media networks"],
        "base_score": 64,
        "why_now": "Frequency shift in urban consumption, retail media monetization, and dense logistics networks.",
        "watch": ["ETERNAL", "SWIGGY", "DMART", "TRENT"],
    },
    {
        "code": "GREEN_HYDROGEN_STORAGE",
        "label": "Green hydrogen and grid storage",
        "sector_code": "ENERGY",
        "queries": ["green hydrogen India", "battery storage tender India", "renewable storage India"],
        "frontier_queries": ["green hydrogen electrolyzer", "long duration energy storage", "grid scale battery storage"],
        "base_score": 62,
        "why_now": "Renewables intermittency, industrial decarbonization, electrolyzer incentives, and storage tenders.",
        "watch": ["RELIANCE", "NTPC", "TATAPOWER", "JSWENERGY", "SUZLON"],
    },
    {
        "code": "GLP1_HEALTHCARE",
        "label": "Metabolic therapies and specialty pharma",
        "sector_code": "HEALTHCARE",
        "queries": ["GLP-1 drugs India pharma", "obesity drug market India", "specialty pharma India"],
        "frontier_queries": ["GLP-1 obesity drugs", "peptide manufacturing", "biosimilar manufacturing"],
        "base_score": 58,
        "why_now": "Global obesity market expansion, peptide capacity, and specialty formulation optionality.",
        "watch": ["SUNPHARMA", "CIPLA", "DRREDDY", "BIOCON"],
    },
]


SOURCE_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "world_bank",
        "label": "World Bank Indicators API",
        "kind": "macro_time_series",
        "url": "https://api.worldbank.org/v2/",
        "docs": "https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structures",
        "cadence": "annual",
        "requires_key": False,
        "status": "connected_with_fallback",
    },
    {
        "id": "gdelt_doc",
        "label": "GDELT DOC 2.0",
        "kind": "global_news_trend_proxy",
        "url": "https://api.gdeltproject.org/api/v2/doc/doc",
        "docs": "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
        "cadence": "near_real_time",
        "requires_key": False,
        "status": "connected_with_timeout_fallback",
    },
    {
        "id": "arxiv",
        "label": "arXiv API",
        "kind": "frontier_research_proxy",
        "url": "https://export.arxiv.org/api/query",
        "docs": "https://info.arxiv.org/help/api/user-manual.html",
        "cadence": "near_real_time",
        "requires_key": False,
        "status": "connected_with_fallback",
    },
    {
        "id": "stooq",
        "label": "Stooq delayed quotes",
        "kind": "commodity_market_proxy",
        "url": "https://stooq.com/q/l/",
        "docs": "https://stooq.com/db/h/",
        "cadence": "delayed_intraday",
        "requires_key": False,
        "status": "connected_where_symbol_available",
    },
    {
        "id": "rbi_mospi_pib",
        "label": "India official releases",
        "kind": "manual_or_future_connector",
        "url": "https://www.rbi.org.in/",
        "docs": "https://www.rbi.org.in/",
        "cadence": "event",
        "requires_key": False,
        "status": "source_registry_only",
    },
    {
        "id": "x_reddit_social",
        "label": "Social trend adapters",
        "kind": "credentialed_social_connector",
        "url": "https://developer.x.com/",
        "docs": "https://developer.x.com/en/docs",
        "cadence": "near_real_time",
        "requires_key": True,
        "status": "adapter_slot_not_configured",
    },
]
